dictionaries = [
    "en_us",
    "pt_br",
    "software-terms",
    "npm",
    "node",
    "typescript",
    "companies",
    "html",
    "css",
    "fonts",
]
words = [
    "chromatic",
    "codebook",
    "codecompanion",
    "csp",
    "cspell",
    "cypress",
    "eslint",
    "figma",
    "formatters",
    "fuelix",
    "gpt",
    "jest",
    "keymap",
    "keymaps",
    "llm",
    "lualine",
    "lucide",
    "markdownlint",
    "matchers",
    "mcp",
    "mcphub",
    "neovim",
    "nextjs",
    "nvim",
    "openai",
    "playwright",
    "postgres",
    "prettier",
    "prisma",
    "pwa",
    "rustc",
    "sonner",
    "sqlite",
    "storybook",
    "supabase",
    "tailwindcss",
    "telus",
    "telusag",
    "testinglibrary",
    "todo",
    "typeorm",
    "vad",
    "vercel",
    "vite",
    "vitest",
    "webpack",
    "xss",
    "zustand",
]
ignore_paths = [
    "target/**/*",
    "**/*.json",
    ".git/**/*",
]
ignore_patterns = [
    '\b[ATCG]+\b',
    '\d{3}-\d{2}-\d{4}',
    "^[A-Z]{2,}$",
    'https?://[^\s]+',
]
